version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "clintonsteiner"

  # Check for docker image updates for caddy-cloudflaredns
  - package-ecosystem: "docker"
    directory: "/caddy-cloudflaredns"
    schedule:
      interval: "daily"
    assignees:
      - "clintonsteiner"

  # Check for docker image updates for jenkinsapi
  - package-ecosystem: "docker"
    directory: "/jenkinsapi"
    schedule:
      interval: "daily"
    assignees:
      - "clintonsteiner"
