name = "docker-monorepo-docs"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "*.example.com", zone_name = "example.com" }
]

[build]
command = "npm run docs:build"
cwd = "/"
watch_paths = ["docs/**/*.md", "*/README.md"]

[build.upload]
format = "modules"
main = "./docs/index.js"
