name = "docker-monorepo-docs"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run docs:build"
cwd = "."
watch_paths = ["src/**/*.astro", "src/**/*.md"]
upload.format = "service-worker"

[env.production]
routes = [
  { pattern = "docker-monorepo.pages.dev", zone_name = "pages.dev" }
]
